spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_study?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none        # 스키마는 SQL 스크립트로 직접 관리
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false